import gensim

text_a=[['Lorem',
  'ipsum',
  'dolor',
  'sit',
  'amet,',
  'consectetur',
  'adipiscing',
  'elit'],
 ['Nullam', 'auctor', 'commodo', 'congue'],
 ['Fusce',
  'hendrerit',
  'risus',
  'mauris,',
  'nec',
  'cursus',
  'enim',
  'molestie',
  'at'],
 ['Mauris',
  'sit',
  'amet',
  'justo',
  'at',
  'nunc',
  'aliquam',
  'molestie',
  'ac',
  'in',
  'massa'],
 ['Nunc', 'non', 'faucibus', 'elit,', 'in', 'ullamcorper', 'tellus'],
 ['Nunc', 'et', 'pulvinar', 'augue,', 'ac', 'mattis', 'lorem'],
 ['Integer',
  'risus',
  'ipsum,',
  'accumsan',
  'vel',
  'sapien',
  'ac,',
  'aliquam',
  'mattis',
  'justo'],
 ['Nulla', 'vitae', 'urna', 'mattis', 'leo', 'posuere', 'lacinia'],
 ['Ut',
  'mauris',
  'nulla,',
  'euismod',
  'sed',
  'mi',
  'eu,',
  'dictum',
  'egestas',
  'est'],
 ['Vivamus', 'auctor', 'non', 'sem', 'eu', 'efficitur'],
 ['Aenean', 'vel', 'tincidunt', 'elit'],
 ['Pellentesque',
  'dui',
  'nisl,',
  'mattis',
  'elementum',
  'dapibus',
  'eu,',
  'maximus',
  'placerat',
  'tellus'],
 ['Phasellus',
  'at',
  'felis',
  'ac',
  'libero',
  'commodo',
  'facilisis',
  'quis',
  'in',
  'elit'],
 ['Proin', 'ac', 'auctor', 'nibh,', 'vitae', 'condimentum', 'eros'],
 ['Pellentesque',
  'pellentesque',
  'eros',
  'sit',
  'amet',
  'ipsum',
  'gravida',
  'efficitur'],
 ['Duis',
  'in',
  'erat',
  'malesuada,',
  'lacinia',
  'justo',
  'vel,',
  'egestas',
  'urna'],
 ['Vivamus', 'quis', 'facilisis', 'nisi'],
 ['Cras', 'in', 'faucibus', 'massa'],
 ['Aenean', 'gravida', 'leo', 'a', 'faucibus', 'ultricies'],
 ['Sed',
  'consectetur',
  'velit',
  'sit',
  'amet',
  'lacus',
  'lobortis',
  'tristique'],
 ['Aenean',
  'vitae',
  'nisl',
  'in',
  'lacus',
  'eleifend',
  'accumsan',
  'vel',
  'non',
  'magna'],
 ['Ut', 'euismod', 'condimentum', 'mauris', 'quis', 'rhoncus'],
 ['In',
  'rhoncus',
  'metus',
  'elit,',
  'eu',
  'vehicula',
  'sapien',
  'commodo',
  'non'],
 ['Phasellus', 'ut', 'sem', 'id', 'elit', 'eleifend', 'suscipit'],
 ['Praesent', 'placerat', 'lorem', 'at', 'accumsan', 'condimentum'],
 ['In', 'vitae', 'sollicitudin', 'velit,', 'vitae', 'ultrices', 'est'],
 ['Orci',
  'varius',
  'natoque',
  'penatibus',
  'et',
  'magnis',
  'dis',
  'parturient',
  'montes,',
  'nascetur',
  'ridiculus',
  'mus'],
 ['Mauris',
  'dolor',
  'est,',
  'pretium',
  'eu',
  'dignissim',
  'eu,',
  'mollis',
  'id',
  'mi'],
 ['Nulla',
  'eu',
  'tortor',
  'nec',
  'nulla',
  'lacinia',
  'tincidunt',
  'at',
  'eget',
  'sapien'],
 ['Praesent',
  'purus',
  'orci,',
  'rhoncus',
  'ut',
  'enim',
  'sed,',
  'tempor',
  'lacinia',
  'enim'],
 ['Aliquam', 'id', 'tempor', 'orci'],
 ['Sed',
  'iaculis',
  'mattis',
  'lectus,',
  'at',
  'luctus',
  'nibh',
  'rutrum',
  'sit',
  'amet'],
 ['Integer',
  'odio',
  'tortor,',
  'venenatis',
  'tristique',
  'egestas',
  'non,',
  'eleifend',
  'eu',
  'lacus'],
 ['Orci',
  'varius',
  'natoque',
  'penatibus',
  'et',
  'magnis',
  'dis',
  'parturient',
  'montes,',
  'nascetur',
  'ridiculus',
  'mus'],
 ['Vestibulum', 'et', 'erat', 'vitae', 'turpis', 'cursus', 'interdum'],
 ['Aenean',
  'fermentum',
  'nulla',
  'orci,',
  'eget',
  'fermentum',
  'sem',
  'varius',
  'lobortis'],
 ['Sed',
  'sit',
  'amet',
  'mauris',
  'sit',
  'amet',
  'arcu',
  'molestie',
  'malesuada'],
 ['In',
  'ultrices,',
  'justo',
  'eget',
  'commodo',
  'dapibus,',
  'arcu',
  'mauris',
  'hendrerit',
  'quam,',
  'nec',
  'viverra',
  'sapien',
  'nibh',
  'quis',
  'neque'],
 ['Phasellus', 'tempor', 'dolor', 'diam'],
 ['Sed', 'sit', 'amet', 'vulputate', 'ante,', 'pharetra', 'commodo', 'diam'],
 ['Nunc', 'luctus', 'odio', 'ac', 'ullamcorper', 'ullamcorper'],
 ['In', 'hac', 'habitasse', 'platea', 'dictumst'],
 ['Suspendisse', 'potenti'],
 ['In', 'id', 'cursus', 'nisi'],
 ['Pellentesque', 'egestas', 'imperdiet', 'ipsum', 'nec', 'luctus'],
 ['Nulla', 'scelerisque', 'elementum', 'congue'],
 ['Praesent', 'sed', 'sodales', 'tortor,', 'a', 'hendrerit', 'risus'],
 ['Duis',
  'gravida,',
  'nunc',
  'et',
  'consectetur',
  'viverra,',
  'arcu',
  'nisl',
  'lobortis',
  'nisl,',
  'id',
  'accumsan',
  'nulla',
  'odio',
  'ut',
  'justo'],
 ['Nam', 'sed', 'lacus', 'sed', 'odio', 'sodales', 'faucibus'],
 ['Maecenas',
  'convallis',
  'accumsan',
  'purus,',
  'vitae',
  'pellentesque',
  'justo',
  'vestibulum',
  'at'],
 ['Fusce',
  'urna',
  'eros,',
  'sodales',
  'ut',
  'est',
  'sit',
  'amet,',
  'posuere',
  'auctor',
  'dui'],
 []]

text_b=[['Lorem',
  'ipsum',
  'dolor',
  'sit',
  'amet,',
  'consectetur',
  'adipiscing',
  'elit'],
 ['Nullam', 'auctor', 'commodo', 'congue'],
 ['Fusce',
  'hendrerit',
  'risus',
  'mauris,',
  'nec',
  'cursus',
  'enim',
  'molestie',
  'at'],
 ['Mauris',
  'sit',
  'amet',
  'justo',
  'at',
  'nunc',
  'aliquam',
  'molestie',
  'ac',
  'in',
  'massa'],
 ['Nunc', 'non', 'faucibus', 'elit,', 'in', 'ullamcorper', 'tellus'],
 ['Nunc', 'et', 'pulvinar', 'augue,', 'ac', 'mattis', 'lorem'],
 ['Integer',
  'risus',
  'ipsum,',
  'accumsan',
  'vel',
  'sapien',
  'ac,',
  'aliquam',
  'mattis',
  'justo'],
 ['Nulla', 'vitae', 'urna', 'mattis', 'leo', 'posuere', 'lacinia'],
 ['Ut',
  'mauris',
  'nulla,',
  'euismod',
  'sed',
  'mi',
  'eu,',
  'dictum',
  'egestas',
  'est'],
 ['Vivamus', 'auctor', 'non', 'sem', 'eu', 'efficitur'],
 ['Aenean', 'vel', 'tincidunt', 'elit'],
 ['Pellentesque',
  'dui',
  'nisl,',
  'mattis',
  'elementum',
  'dapibus',
  'eu,',
  'maximus',
  'placerat',
  'tellus'],
 ['Phasellus',
  'at',
  'felis',
  'ac',
  'libero',
  'commodo',
  'facilisis',
  'quis',
  'in',
  'elit'],
 ['Proin', 'ac', 'auctor', 'nibh,', 'vitae', 'condimentum', 'eros'],
 ['Pellentesque',
  'pellentesque',
  'eros',
  'sit',
  'amet',
  'ipsum',
  'gravida',
  'efficitur'],
 ['Duis',
  'in',
  'erat',
  'malesuada,',
  'lacinia',
  'justo',
  'vel,',
  'egestas',
  'urna'],
 ['Vivamus', 'quis', 'facilisis', 'nisi'],
 ['Cras', 'in', 'faucibus', 'massa'],
 ['Aenean', 'gravida', 'leo', 'a', 'faucibus', 'ultricies'],
 ['Sed',
  'consectetur',
  'velit',
  'sit',
  'amet',
  'lacus',
  'lobortis',
  'tristique'],
 ['Aenean',
  'vitae',
  'nisl',
  'in',
  'lacus',
  'eleifend',
  'accumsan',
  'vel',
  'non',
  'magna'],
 ['Ut', 'euismod', 'condimentum', 'mauris', 'quis', 'rhoncus'],
 ['In',
  'rhoncus',
  'metus',
  'elit,',
  'eu',
  'vehicula',
  'sapien',
  'commodo',
  'non'],
 ['Phasellus', 'ut', 'sem', 'id', 'elit', 'eleifend', 'suscipit'],
 ['Praesent', 'placerat', 'lorem', 'at', 'accumsan', 'condimentum'],
 ['In', 'vitae', 'sollicitudin', 'velit,', 'vitae', 'ultrices', 'est'],
 ['Orci',
  'varius',
  'natoque',
  'penatibus',
  'et',
  'magnis',
  'dis',
  'parturient',
  'montes,',
  'nascetur',
  'ridiculus',
  'mus'],
 ['Mauris',
  'dolor',
  'est,',
  'pretium',
  'eu',
  'dignissim',
  'eu,',
  'mollis',
  'id',
  'mi'],
 ['Nulla',
  'eu',
  'tortor',
  'nec',
  'nulla',
  'lacinia',
  'tincidunt',
  'at',
  'eget',
  'sapien'],
 ['Praesent',
  'purus',
  'orci,',
  'rhoncus',
  'ut',
  'enim',
  'sed,',
  'tempor',
  'lacinia',
  'enim'],
 ['Aliquam', 'id', 'tempor', 'orci'],
 ['Sed',
  'iaculis',
  'mattis',
  'lectus,',
  'at',
  'luctus',
  'nibh',
  'rutrum',
  'sit',
  'amet'],
 ['Integer',
  'odio',
  'tortor,',
  'venenatis',
  'tristique',
  'egestas',
  'non,',
  'eleifend',
  'eu',
  'lacus'],
 ['Orci',
  'varius',
  'natoque',
  'penatibus',
  'et',
  'magnis',
  'dis',
  'parturient',
  'montes,',
  'nascetur',
  'ridiculus',
  'mus'],
 ['Vestibulum', 'et', 'erat', 'vitae', 'turpis', 'cursus', 'interdum'],
 ['Aenean',
  'fermentum',
  'nulla',
  'orci,',
  'eget',
  'fermentum',
  'sem',
  'varius',
  'lobortis'],
 ['Sed',
  'sit',
  'amet',
  'mauris',
  'sit',
  'amet',
  'arcu',
  'molestie',
  'malesuada'],
 ['In',
  'ultrices,',
  'justo',
  'eget',
  'commodo',
  'dapibus,',
  'arcu',
  'mauris',
  'hendrerit',
  'quam,',
  'nec',
  'viverra',
  'sapien',
  'nibh',
  'quis',
  'neque'],
 ['Phasellus', 'tempor', 'dolor', 'diam'],
 ['Sed', 'sit', 'amet', 'vulputate', 'ante,', 'pharetra', 'commodo', 'diam'],
 ['Nunc', 'luctus', 'odio', 'ac', 'ullamcorper', 'ullamcorper'],
 ['In', 'hac', 'habitasse', 'platea', 'dictumst'],
 ['Suspendisse', 'potenti'],
 ['In', 'id', 'cursus', 'nisi'],
 ['Pellentesque', 'egestas', 'imperdiet', 'ipsum', 'nec', 'luctus'],
 ['Nulla', 'scelerisque', 'elementum', 'congue'],
 ['Praesent', 'sed', 'sodales', 'tortor,', 'a', 'hendrerit', 'risus'],
 ['Duis',
  'gravida,',
  'nunc',
  'et',
  'consectetur',
  'viverra,',
  'arcu',
  'nisl',
  'lobortis',
  'nisl,',
  'id',
  'accumsan',
  'nulla',
  'odio',
  'ut',
  'justo'],
 ['Nam', 'sed', 'lacus', 'sed', 'odio', 'sodales', 'faucibus'],
 ['Maecenas',
  'convallis',
  'accumsan',
  'purus,',
  'vitae',
  'pellentesque',
  'justo',
  'vestibulum',
  'at'],
 ['Fusce',
  'urna',
  'eros,',
  'sodales',
  'ut',
  'est',
  'sit',
  'amet,',
  'posuere',
  'auctor',
  'dui'],
 []]

text_c=text_a

model_a=gensim.models.Word2Vec(text_a, window=5, min_count=1, iter=25)
model_b=gensim.models.Word2Vec(text_b, window=5, min_count=1, iter=25)
model_c=gensim.models.Word2Vec(text_c, window=5, min_count=1, iter=25)
model_c.reset_from(model_a)
model_c.train(text_a, total_examples=model_c.corpus_count, epochs=25)